### ISSUE TITLE
Add Comments in your python code

### ISSUE THREAD

**Issue by esaiaswt** [JAW-05/Ping-Pong-Game#4]
Please add comments as documentation in your python code.  This is to help you and other users to understand your code better.

**Comment by JAW-05** [comment]
Updated, thanks!

**Comment by esaiaswt** [comment]
There is no comments in your .py file.... comments is like this:
`# This is a comment in code which helps everyone to understand the codes better`

**Comment by JAW-05** [comment]
![comments](https://github.com/user-attachments/assets/4b0c34a2-0265-446f-a56a-931ff91c403a)
I thought I have already added comments, isn't it supposed to be like this?
