### ISSUE TITLE
MP3 file not in GitHub 

### ISSUE THREAD

**Issue by esaiaswt** [JAW-05/Ping-Pong-Game#8]
Here is the error message:
pygame 2.6.0 (SDL 2.28.4, Python 3.10.8)
Hello from the pygame community. https://www.pygame.org/contribute.html
Font not found at PressStart2P-Regular.ttf, using default font.
Traceback (most recent call last):
  File "c:\Users\esaia\OneDrive\Documents\projects\Ping-Pong-Game-2\pingpong.py", line 41, in <module>
    pygame.mixer.music.load('8bit.mp3')
pygame.error: No file '8bit.mp3' found in working directory 'C:\Users\esaia\OneDrive\Documents\projects\Ping-Pong-Game-2'.

**Comment by JAW-05** [comment]
![Screenshot 2024-07-24 120828](https://github.com/user-attachments/assets/bed7dcf6-b152-450c-a398-461bc0858a84)

![Screenshot 2024-07-24 120418](https://github.com/user-attachments/assets/98134417-0a92-41bf-9ecd-0606f8aa31ca)

Hi, you will have to **directly download** each MP3 file and font from the **assets folder**. It should work after, I could download all the necessary files like that. 

Please review it and feel free to share any additional feedback. Thank you!

**Comment by JAW-05** [comment]
Hi, I have fixed the issue by removing the assets folder. Please do review it and feel free to share any additional feedback. Thank you!
